# Übersetzungen: num -> (en_name, fr_name, it_name, en_desc, fr_desc, it_desc)
FOOD = {
 6:("Garlic bread","Pain à l'ail","Pane all'aglio",
    "with sour cream dip","avec dip à la crème fraîche","con salsa di panna acida"),
 8:("Baked sheep's cheese","Fromage de brebis gratiné","Formaggio di pecora gratinato",
    "on tomatoes and peppers with olive oil, served with bread","sur tomates et poivrons à l'huile d'olive, servi avec du pain","su pomodori e peperoni con olio d'oliva, con pane"),
 9:("Gambas Picante","Gambas Picante","Gambas Picante",
    "in house sauce, with garlic, served with bread","dans une sauce maison, à l'ail, servi avec du pain","in salsa della casa, con aglio, con pane"),
 10:("Goat's cheese","Fromage de chèvre","Formaggio di capra",
    "baked with honey and walnuts, served with bread","gratiné au miel et aux noix, servi avec du pain","gratinato con miele e noci, con pane"),
 11:("Beef carpaccio","Carpaccio de bœuf","Carpaccio di manzo",
    "slices of beef fillet on balsamic dressing, with grated Parmesan, capers and rocket, served with bread","fines tranches de filet de bœuf sur vinaigrette balsamique, parmesan râpé, câpres et roquette, servi avec du pain","fettine di filetto di manzo su condimento balsamico, con parmigiano grattugiato, capperi e rucola, con pane"),
 13:("Chicken soup","Soupe de poulet","Zuppa di pollo","","",""),
 14:("Soup of the day","Soupe du jour","Zuppa del giorno","","",""),
 16:("Beef fillet salad","Salade au filet de bœuf","Insalata con filetto di manzo",
    "mixed salad with homemade vinaigrette, strips of fillet and rump steak, Mediterranean vegetables and Parmesan","salade mêlée à la vinaigrette maison, lamelles de filet et de romsteck, légumes méditerranéens et parmesan","insalata mista con vinaigrette fatta in casa, striscioline di filetto e controfiletto, verdure mediterranee e parmigiano"),
 17:("Chef's salad","Salade du chef","Insalata dello chef",
    "mixed salad with homemade vinaigrette, chicken strips, fried potatoes and Parmesan","salade mêlée à la vinaigrette maison, émincé de poulet, pommes de terre sautées et parmesan","insalata mista con vinaigrette fatta in casa, striscioline di pollo, patate arrosto e parmigiano"),
 19:("Vegetable platter","Assiette de légumes","Piatto di verdure",
    "colourful pan-fried vegetables, baked potato with sour cream and a side salad","poêlée de légumes variés, pomme de terre au four à la crème et salade d'accompagnement","verdure miste in padella, patata al forno con panna acida e insalata di contorno"),
 21:("Tagliatelle with prawns","Tagliatelles aux gambas","Tagliatelle con gamberi",
    "fresh ribbon pasta with prawns and cherry tomatoes in a Parmesan cream sauce, with a side salad","pâtes fraîches aux gambas et tomates cerises, sauce crème au parmesan, avec salade","pasta fresca con gamberi e pomodorini in salsa di panna al parmigiano, con insalata"),
 22:("Gentlemen's plate","Assiette « Monsieur »","Piatto del signore",
    "2 pork fillet medallions with pepper sauce and fried potatoes","2 médaillons de filet de porc, sauce au poivre, pommes de terre sautées","2 medaglioni di filetto di maiale con salsa al pepe e patate arrosto"),
 23:("Ladies' plate","Assiette « Madame »","Piatto della signora",
    "chicken steak and tropical fruit gratinated with hollandaise sauce and cheese, with croquettes and vegetables","steak de poulet et fruits tropicaux gratinés à la sauce hollandaise et fromage, croquettes et légumes","bistecca di pollo e frutta tropicale gratinati con salsa olandese e formaggio, con crocchette e verdure"),
 24:("Mini fillet steak","Mini filet de bœuf","Filetto mini",
    "with fresh mushrooms in a creamy pepper sauce and fried potatoes","champignons frais, sauce crème au poivre, pommes de terre sautées","con funghi freschi in salsa cremosa al pepe e patate arrosto"),
 25:("Lamb rump","Hanche d'agneau","Fesa d'agnello",
    "with fresh garlic, green beans and fried potatoes","à l'ail frais, haricots verts et pommes de terre sautées","con aglio fresco, fagiolini e patate arrosto"),
 26:("Mixed lamb plate","Assiette d'agneau mixte","Piatto misto d'agnello",
    "steak and cutlet with fresh garlic, green beans and fried potatoes","steak et côtelette à l'ail frais, haricots verts et pommes de terre sautées","bistecca e costoletta con aglio fresco, fagiolini e patate arrosto"),
 27:("Lamb cutlets","Côtelettes d'agneau","Costolette d'agnello",
    "from the rack, with fresh garlic, green beans and fried potatoes","du carré, à l'ail frais, haricots verts et pommes de terre sautées","dal carré, con aglio fresco, fagiolini e patate arrosto"),
 29:("Rump steak","Romsteck","Controfiletto",
    "with herb butter and baked potato with sour cream","beurre aux herbes, pomme de terre au four à la crème","con burro alle erbe e patata al forno con panna acida"),
 30:("Fillet steak","Filet de bœuf","Filetto",
    "with herb butter and baked potato with sour cream","beurre aux herbes, pomme de terre au four à la crème","con burro alle erbe e patata al forno con panna acida"),
 31:("“Am Fels” pan","Poêlée « Am Fels »","Padella «Am Fels»",
    "rump and fillet strips, peppers and fresh mushrooms in a fiery pepper salsa, with buttered rice","lamelles de romsteck et filet, poivrons et champignons frais dans une salsa relevée, riz au beurre","straccetti di controfiletto e filetto, peperoni e funghi freschi in salsa piccante, con riso al burro"),
 33:("Roast beef with onions","Rumsteck aux oignons","Controfiletto con cipolle",
    "rump steak with fresh roasted onions and fried potatoes","romsteck aux oignons frais rôtis, pommes de terre sautées","controfiletto con cipolle fresche arrostite e patate arrosto"),
 35:("Fillet steak Madagascar","Filet de bœuf Madagascar","Filetto Madagascar",
    "with pepper sauce and fried potatoes","sauce au poivre, pommes de terre sautées","con salsa al pepe e patate arrosto"),
 36:("Fillet steak with mushrooms","Filet de bœuf aux champignons","Filetto ai funghi",
    "with creamy mushroom sauce, croquettes and vegetables","sauce crème aux champignons, croquettes et légumes","con salsa cremosa ai funghi, crocchette e verdure"),
 37:("Rump steak “Special”","Romsteck « Spécial »","Controfiletto «Speciale»",
    "with roasted mushrooms and a touch of béarnaise sauce, with fries","champignons rôtis et une touche de sauce béarnaise, frites","con funghi arrostiti e un tocco di salsa bearnese, con patatine"),
 38:("“India” pan","Poêlée « India »","Padella «India»",
    "sliced chicken with tropical fruit in a delicate curry cream sauce, with buttered rice","émincé de poulet aux fruits tropicaux, sauce crème au curry, riz au beurre","straccetti di pollo con frutta tropicale in delicata salsa al curry e panna, con riso al burro"),
 39:("Escalope Viennese style","Escalope viennoise","Cotoletta alla viennese",
    "breaded, with fries","panée, frites","impanata, con patatine"),
 40:("Escalope with mushrooms","Escalope aux champignons","Cotoletta ai funghi",
    "breaded, with creamy mushroom sauce and fries","panée, sauce crème aux champignons, frites","impanata, con salsa cremosa ai funghi e patatine"),
 42:("Plain chicken steak","Steak de poulet nature","Bistecca di pollo al naturale",
    "grilled, with herb butter and baked potato with sour cream","grillé, beurre aux herbes, pomme de terre au four à la crème","grigliata, con burro alle erbe e patata al forno con panna acida"),
 43:("Cordon Bleu","Cordon-bleu","Cordon Bleu",
    "pork fillet filled with ham and cheese, breaded, with fries","filet de porc farci au jambon et fromage, pané, frites","filetto di maiale ripieno di prosciutto e formaggio, impanato, con patatine"),
 44:("Zagreb plate","Assiette Zagreb","Piatto Zagabria",
    "pork fillet filled with ham and cheese in a creamy garlic sauce, with fried potatoes","filet de porc farci au jambon et fromage, sauce crème à l'ail, pommes de terre sautées","filetto di maiale ripieno di prosciutto e formaggio in salsa cremosa all'aglio, con patate arrosto"),
 45:("Zhivago plate","Assiette Jivago","Piatto Živago",
    "pork fillet with creamy mushroom sauce, croquettes and vegetables","filet de porc, sauce crème aux champignons, croquettes et légumes","filetto di maiale con salsa cremosa ai funghi, crocchette e verdure"),
 46:("Marco Polo","Marco Polo","Marco Polo",
    "pork fillet gratinated with ham, béarnaise sauce and cheese, with fried potatoes","filet de porc gratiné au jambon, sauce béarnaise et fromage, pommes de terre sautées","filetto di maiale gratinato con prosciutto, salsa bearnese e formaggio, con patate arrosto"),
 51:("Maya the Bee","Maya l'abeille","Ape Maia",
    "breaded chicken escalope with fries","escalope de poulet panée avec frites","cotoletta di pollo impanata con patatine"),
 53:("Cowboy","Cowboy","Cowboy",
    "4 cevapcici with fries","4 cevapcici avec frites","4 cevapcici con patatine"),
 54:("Cevapcici","Cevapcici","Cevapcici",
    "homemade minced-meat rolls with fries and djuvec rice","rouleaux de viande hachée maison, frites et riz djuvec","involtini di carne macinata fatti in casa, con patatine e riso djuvec"),
 55:("Raznjici","Raznjici","Raznjici",
    "pork skewers with fries and djuvec rice","brochettes de porc, frites et riz djuvec","spiedini di maiale, con patatine e riso djuvec"),
 56:("Shepherd's-style minced steak","Steak haché « à la bergère »","Hamburger alla pastora",
    "filled with sheep's cheese, with fries and djuvec rice","farci au fromage de brebis, frites et riz djuvec","ripieno di formaggio di pecora, con patatine e riso djuvec"),
 57:("Mixed grill platter","Assiette grillades","Grigliata mista",
    "cevapcici, loin steak, minced steak and raznjici, with djuvec rice and fries","cevapcici, steak d'échine, steak haché et raznjici, riz djuvec et frites","cevapcici, bistecca di lonza, hamburger e raznjici, con riso djuvec e patatine"),
 58:("Calf's liver","Foie de veau","Fegato di vitello",
    "with fresh roasted onions, fries and djuvec rice","oignons frais rôtis, frites et riz djuvec","con cipolle fresche arrostite, patatine e riso djuvec"),
 59:("“Merry Bosnian”","« Joyeux Bosniaque »","«Bosniaco allegro»",
    "rump steak filled with ham and cheese, with fries and djuvec rice","romsteck farci au jambon et fromage, frites et riz djuvec","controfiletto ripieno di prosciutto e formaggio, con patatine e riso djuvec"),
 60:("Pike-perch fillet","Filet de sandre","Filetto di lucioperca",
    "with olive oil and herb butter, with chard potatoes and garlic","sauce fine à l'aneth, pommes de terre aux blettes et à l'ail","in delicata salsa all'aneto, con patate e bietola all'aglio"),
 61:("Salmon fillet","Filet de saumon","Filetto di salmone",
    "with herb butter and baked potato with sour cream","beurre aux herbes, pomme de terre au four à la crème","con burro alle erbe e patata al forno con panna acida"),
 62:("Grilled Scampi","Scampis grillés","Scampi alla griglia",
    "with fresh garlic and olive oil, with chard potatoes","à l'ail frais et huile d'olive, pommes de terre aux blettes","con aglio fresco e olio d'oliva, con patate e bietola"),
 63:("Fish platter","Assiette de poisson","Piatto di pesce",
    "assorted fish fillets and 2 prawns in herb butter, with chard potatoes and garlic","filets de poissons variés et 2 gambas au beurre d'herbes, pommes de terre aux blettes et à l'ail","filetti di pesce misti e 2 gamberi al burro d'erbe, con patate e bietola all'aglio"),
 64:("Pancakes with chocolate","Crêpes au chocolat","Crêpe al cioccolato","","",""),
 65:("Pancakes with jam","Crêpes à la confiture","Crêpe alla marmellata","","",""),
 66:("Ice cream with hot cherries","Glace aux cerises chaudes","Gelato con ciliegie calde",
    "with vanilla ice cream and cream","avec glace vanille et crème","con gelato alla vaniglia e panna"),
 67:("Gourmet pancake","Crêpe gourmande","Crêpe gourmet",
    "wafer-thin pancake with chocolate, filled with vanilla ice cream, decorated with fruit and cream","crêpe très fine au chocolat, garnie de glace vanille, décorée de fruits et de crème","crêpe sottilissima al cioccolato, farcita con gelato alla vaniglia, decorata con frutta e panna"),
 68:("Crème brûlée","Crème brûlée","Crème brûlée",
    "with a caramelised sugar crust","avec couche de sucre caramélisé","con crosta di zucchero caramellato"),
 69:("Lava cake","Fondant au chocolat","Tortino al cioccolato",
    "warm chocolate soufflé with a molten centre, with vanilla ice cream and cream","soufflé chaud au chocolat au cœur coulant, glace vanille et crème","soufflé caldo al cioccolato dal cuore morbido, con gelato alla vaniglia e panna"),
 70:("Semifreddo","Semifreddo","Semifreddo",
    "airy like a mousse, creamy like ice cream, with caramelised almonds and homemade caramel sauce on a biscuit base","aérien comme une mousse, crémeux comme une glace, amandes caramélisées et sauce caramel maison sur fond de biscuit","soffice come una mousse, cremoso come un gelato, con mandorle caramellate e salsa al caramello fatta in casa su base di biscotto"),
}

# Beilagen / Saucen: name -> "EN · FR · IT"
SIDES = {
 "Pommes Frites":"Fries · Frites · Patatine fritte",
 "Kroketten":"Croquettes · Croquettes · Crocchette",
 "Bratkartoffeln":"Fried potatoes · Pommes de terre sautées · Patate arrosto",
 "Folienkartoffel":"Baked potato · Pomme de terre au four · Patata al forno",
 "Mangold-Kartoffeln":"Chard potatoes · Pommes de terre aux blettes · Patate con bietola",
 "Butterreis":"Buttered rice · Riz au beurre · Riso al burro",
 "Djuwetschreis":"Djuvec rice · Riz djuvec · Riso djuvec",
 "Gemüse":"Vegetables · Légumes · Verdure",
 "Prinzessbohnen":"Green beans · Haricots verts · Fagiolini",
 "Geröstete Champignons":"Roasted mushrooms · Champignons rôtis · Funghi arrostiti",
 "Röstzwiebeln":"Fried onions · Oignons frits · Cipolle fritte",
 "Beilagensalat":"Side salad · Salade · Insalata di contorno",
 "Kräuterbutter":"Herb butter · Beurre aux herbes · Burro alle erbe",
 "Ajvar":"Ajvar · Ajvar · Ajvar",
 "Sauerrahm":"Sour cream · Crème fraîche · Panna acida",
 "Champignonsauce":"Mushroom sauce · Sauce aux champignons · Salsa ai funghi",
 "Pfeffersauce":"Pepper sauce · Sauce au poivre · Salsa al pepe",
 "Hollandaise":"Hollandaise · Hollandaise · Olandese",
 "Béarnaise":"Béarnaise · Béarnaise · Bearnese",
 "Rahmsauce":"Cream sauce · Sauce crème · Salsa alla panna",
}

# Kategorie-Untertitel (unter dem cat-title): "EN · FR · IT"
CATSUB = {
 "Vorspeisen":"Starters & Soups · Entrées & Soupes · Antipasti e Zuppe",
 "Salate":"Salads & Light Dishes · Salades & Plats légers · Insalate e Piatti leggeri",
 "Lamm":"Lamb · Agneau · Agnello",
 "Steak":"Premium Steaks · Steaks premium · Bistecche premium",
 "Hähnchen":"Chicken & Pork · Poulet & Porc · Pollo e Maiale",
 "Grill":"Grill Specialities · Spécialités grillées · Specialità alla griglia",
 "Fisch":"Fresh Fish · Poisson frais · Pesce fresco",
 "Desserts":"Desserts · Desserts · Dolci",
 "Getränke":"Drinks · Boissons · Bevande",
 "Rot- &":"Red & Rosé wines · Vins rouges & rosés · Vini rossi e rosati",
 "Weißweine":"White wines & Sparkling · Vins blancs & Mousseux · Vini bianchi e Spumante",
 "Aperitifs":"Aperitifs & Spirits · Apéritifs & Spiritueux · Aperitivi e Distillati",
}
# Subhead-Übersetzungen
SUBTR = {
 "Suppen":"Soups · Soupes · Zuppe",
 "Für unsere kleinen Gäste":"For our little guests · Pour nos petits convives · Per i nostri piccoli ospiti",
 "Für unsere Senioren":"For our senior guests · Pour nos aînés · Per i nostri ospiti senior",
 "Vom Schwein":"Pork · Porc · Maiale",
 "Hähnchen & Schnitzel":"Chicken & Escalopes · Poulet & Escalopes · Pollo e Cotolette",
 "Beilagen":"Side dishes · Accompagnements · Contorni",
 "Saucen & Dips":"Sauces & Dips · Sauces & Dips · Salse e Dip",
 "Saucen":"Sauces · Sauces · Salse",
 "Kaffee & Heißgetränke":"Coffee & Hot drinks · Café & Boissons chaudes · Caffè e Bevande calde",
 "Alkoholfreie Getränke":"Soft drinks · Boissons sans alcool · Bevande analcoliche",
 "Biere":"Beers · Bières · Birre",
 "Rotweine":"Red wines · Vins rouges · Vini rossi",
 "Weißweine":"White wines · Vins blancs · Vini bianchi",
 "Roséweine":"Rosé wines · Vins rosés · Vini rosati",
 "Sekt":"Sparkling · Mousseux · Spumante",
 "Aperitifs":"Aperitifs · Apéritifs · Aperitivi",
 "Liköre & Bitter":"Liqueurs & Bitters · Liqueurs & Amers · Liquori e Amari",
 "Spirituosen":"Spirits · Spiritueux · Distillati",
 "Cognac & Weinbrand":"Cognac & Brandy · Cognac & Eau-de-vie · Cognac e Brandy",
}

# Wein-Beschreibungen: deutscher Text -> (EN, FR, IT)
WINEDESC = {
 "fruchtiges Aroma reifer roter Beeren, sanft, elegant und gut balanciert · trocken":
   ("fruity aroma of ripe red berries, smooth, elegant and well balanced · dry",
    "arôme fruité de baies rouges mûres, souple, élégant et bien équilibré · sec",
    "aroma fruttato di bacche rosse mature, morbido, elegante e ben bilanciato · secco"),
 "fein trockener, leichter Wein":
   ("delicately dry, light wine","vin léger, finement sec","vino leggero, finemente secco"),
 "rund und weich, feines sanftes Aroma · lieblich":
   ("round and soft, fine gentle aroma · sweet","rond et doux, arôme fin et délicat · moelleux","rotondo e morbido, aroma fine e delicato · amabile"),
 "fruchtig mit ausbalancierter Süße, nicht ganz trocken":
   ("fruity with balanced sweetness, off-dry","fruité avec une douceur équilibrée, demi-sec","fruttato con dolcezza equilibrata, non del tutto secco"),
 "Frucht und Tannin mit Beeren, saftiger junger Spanier":
   ("fruit and tannin with berries, a juicy young Spaniard","fruit et tanin avec des baies, jeune espagnol juteux","frutto e tannino con bacche, giovane spagnolo succoso"),
 "intensive Noten roter Früchte, weich und rund":
   ("intense notes of red fruit, soft and round","notes intenses de fruits rouges, souple et rond","note intense di frutta rossa, morbido e rotondo"),
 "frisch, mit Aroma tropischer Früchte · trocken":
   ("fresh, with tropical fruit aroma · dry","frais, arôme de fruits tropicaux · sec","fresco, con aroma di frutta tropicale · secco"),
 "saftig und animierend frisch, lang im Abgang · trocken":
   ("juicy and invigoratingly fresh, long finish · dry","juteux et vif, longue finale · sec","succoso e vivace, lungo finale · secco"),
 "kräftige Früchte und zart süßlicher Schmelz · feinherb":
   ("bold fruit and a delicate sweet smoothness · off-dry","fruits intenses et douceur délicate · demi-sec","frutta intensa e delicata morbidezza dolce · semisecco"),
 "frisch, sehr aromatisch, tropische Früchte · feinherb":
   ("fresh, very aromatic, tropical fruit · off-dry","frais, très aromatique, fruits tropicaux · demi-sec","fresco, molto aromatico, frutta tropicale · semisecco"),
 "frisch, mit Melonen- und Ananasaromen · lieblich":
   ("fresh, with melon and pineapple aromas · sweet","frais, arômes de melon et d'ananas · moelleux","fresco, con aromi di melone e ananas · amabile"),
 "Trebbiano, frisch, trocken und ausdrucksstark, zitrusfruchtig mit Mandelaromen":
   ("Trebbiano, fresh, dry and expressive, citrusy with almond notes","Trebbiano, frais, sec et expressif, agrumes et notes d'amande","Trebbiano, fresco, secco ed espressivo, agrumato con note di mandorla"),
 "erfrischende Frucht, leichter Genuss · trocken":
   ("refreshing fruit, light and easy · dry","fruit rafraîchissant, plaisir léger · sec","frutto rinfrescante, piacere leggero · secco"),
 "fruchtige Aromen von Waldbeeren, Erdbeeren und Kirschen":
   ("fruity aromas of wild berries, strawberries and cherries","arômes fruités de baies des bois, fraises et cerises","aromi fruttati di frutti di bosco, fragole e ciliegie"),
 "Walderdbeeren, Himbeeren, Kirschen und florale Noten":
   ("wild strawberries, raspberries, cherries and floral notes","fraises des bois, framboises, cerises et notes florales","fragoline di bosco, lamponi, ciliegie e note floreali"),
 "fruchtig und mild · trocken":
   ("fruity and mild · dry","fruité et doux · sec","fruttato e delicato · secco"),
}
